### ISSUE TITLE
Property 'apply' is missing in type 'HtmlWebpackPlugin' but required in type 'Plugin'

### ISSUE THREAD

**Issue by artemirq** [jantimon/html-webpack-plugin#1244]
## Expected behaviour

No TypeScript errors

## Current behaviour

After [this](https://github.com/jantimon/html-webpack-plugin/commit/d4eb1c749316af3964126606fe6c70a233c30fef) commit, when I try build [my project](https://github.com/artemirq/zero-scriptsjs/pull/389) I get this error:

``` error TS2741: Property 'apply' is missing in type 'HtmlWebpackPlugin' but required in type 'Plugin'.```

## Environment

Node.js v12.1.0
win32 10.0.15063

## Additional context

I think, if we revert this commit, problem should be fixed :)

**Comment by jantimon** [comment]
Using @types/webpack caused multiple problems - maybe we could just add the apply method?

**Comment by artemirq** [comment]
@jantimon Good idea

**Comment by MrStLouis** [comment]
I just ran into this as well, following for fix :)

**Comment by jantimon** [comment]
Released in 4.0.0-beta.8
