### ISSUE TITLE
v5.6.5 changes in evaluateCompilationResult break partial compilation with handlebars-loader

### ISSUE THREAD

**Issue by hatelamers** [jantimon/html-webpack-plugin#1881]
## Current behaviour 💣
When using Handlebars with the 5.6.5 version like
```javascript
module: {
  loaders: [
    { test: /\.hbs$/, loader: "handlebars-loader" }
  ]
},
plugins: [
  new HtmlWebpackPlugin({
    title: 'Custom template using Handlebars',
    template: 'index.hbs'
  })
]
```
any partial included in `index.hbs`:
```hbs
<html><body>{{> SomePartial}}</body></html>
```
would cause compilation error
```log
Error: The partial SomePartial could not be compiled when running in runtime-only mode
```
Further investigation revealed that changes to `vmContext` in the function `evaluateCompilationResult` is the primary cause of Handlebars failing to compile. If I change line 643 in `index.js` from
```javascript
Object.assign(globalClone, {
```
to
```javascript
Object.assign({}, global, {
```
the full functionality of Handlebars is restored.

## Expected behaviour ☀️
Handlebar templates with partial includes should compile after update from v5.6.4.

### Reproduction Example 👾
Just use your own HBS example extended with a partial.

## Environment 🖥
Node.js v22.17.0
win32 10.0.19044
NPM 10.9.2
Webpack 5.104.1
html-webpack-plugin 5.6.5

**Comment by hatelamers** [comment]
> PR welcome

I would be happy to provide one, however my "fix" would essentially roll back `index.js` to the v5.6.4, while I suppose there was a good reason for the change - I just don't quite get it.
