### ISSUE TITLE
Build falls after upgrading webpack to v4

### ISSUE THREAD

**Issue by finom** [jantimon/html-webpack-plugin#860]
Subj. The usage of the plugin is regular. I will provide more info if needed.

### Error Message & Stack Trace

```
/Users/finom/Work/djavan-front-end/node_modules/html-webpack-plugin/lib/compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
                                                  ^

TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /Users/finom/Work/djavan-front-end/node_modules/html-webpack-plugin/lib/compiler.js:81:51
    at compile (/Users/finom/Work/djavan-front-end/node_modules/webpack/lib/Compiler.js:222:11)
    at hooks.afterCompile.callAsync.err (/Users/finom/Work/djavan-front-end/node_modules/webpack/lib/Compiler.js:470:14)
```

**Comment by drihup** [comment]
By now, it's incompatible with webpack v4 [webpack v4 migration plan #816](https://github.com/jantimon/html-webpack-plugin/issues/816), but they're working on there. It seems @jantimon is wrking outside and can't commit the new changes. By the moment you can try installing [webpack-contrib/html-webpack-plugin](https://github.com/webpack-contrib/html-webpack-plugin). It has committed the new changes til jantimon's back.
`npm install webpack-contrib/html-webpack-plugin`
It works for me.

**Comment by MadOgre** [comment]
Please fix this. I can't use webpack 4 without it. The webpack-contrib/html-webpack-plugin is broken too

**Comment by kaiyoma** [comment]
Ran into this also via `yarn check`:

```
error "html-webpack-plugin#webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3" doesn't satisfy found match of "webpack@4.0.0"
```

**Comment by haishengXie0712** [comment]
You can specify that you can use webpack@3.10.0 to support the html-webpack-plugin.

**Comment by ronkorving** [comment]
@haishengXie0712 I think the whole point is that people want to upgrade to Webpack 4 :)

**Comment by haishengXie0712** [comment]
It may not be supported for a while, so use it first.

**Comment by insomnia1337** [comment]
> It's still Error: Child compilation failed, 

when they are going to fix that issue?

**Comment by shongololo** [comment]
See the [blog post](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) and scroll down to "If you use HtmlWebpackPlugin" for background.

**Comment by lovetingyuan** [comment]
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202
compatibility for plugins or loaders is not that satisfactory

**Comment by Dinfyru** [comment]
+1

**Comment by wiseguy** [comment]
I had to downgrade webpack-dev-server as well. 2.11.0 worked so settled for that.

**Comment by yyynnn** [comment]
`webpack-contrib/html-webpack-plugin` install in yarn gives me this error: 

`An unexpected error occurred: "https://github.com/webpack-contrib/html-webpack-plugin: self signed certificate in certificate chain".`

same in npm

**Comment by atilkan** [comment]
+1
<img width="771" alt="screen shot 2018-02-28 at 15 52 11" src="https://user-images.githubusercontent.com/1254613/36788606-9c2b41e2-1c9f-11e8-82cc-152d1bc7f767.png">

**Comment by jantimon** [comment]
We are trying to release html-webpack-plugin 3.0 until the mid/end of this week

**Comment by garrettmaring** [comment]
This seems to still be an issue.

```
"html-webpack-plugin": "^3.2.0",
"webpack": "^4.8.2"
```
