### ISSUE TITLE
Can't load plugins using webpack 4

### ISSUE THREAD

**Issue by Gisleburt** [jantimon/html-webpack-plugin#887]
## Description

Fails to load plugins in Webpack 4.

Configuration works in webpack 3.11.0

### Error Message & Stack Trace

This is output in the HTML:

```html
Html Webpack Plugin:
<pre>  TypeError: callback is not a function
  
  - main.js:57 compilation.plugin
    [profile]/[webpack-cdn-plugin]/main.js:57:9
  
  
  - new Promise
  
  
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [profile]/[tapable]/lib/Hook.js:35:21
  
  - index.js:647 
    [profile]/[html-webpack-plugin]/index.js:647:47
  
  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [profile]/[html-webpack-plugin]/index.js:162:36
  
  
  - next_tick.js:160 process._tickCallback
    internal/process/next_tick.js:160:7
  
</pre>
```

The contents of the pre tags also appears in the cli in red.

### Config

Copy the relevant section from `webpack.config.js`:

```js
module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: __dirname + '/src/index.html',
      title: 'Apolitical Profiles',
    }),
    new WebpackCdnPlugin({
      prod,
      modules: {
        'react': [
          { name: 'react', var: 'React', path: `umd/react.${cdnEnv}.js` },
          { name: 'react-dom', var: 'ReactDOM', path: `umd/react-dom.${cdnEnv}.js` },
        ]
      },
      publicPath: '/node_modules'
    }),
  ],
}
```

Copy your template file:

Probably irrelevant but 🤷🏻‍♂️ 

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>
</head>
<body>
<div id="profile-app">

</div>
</body>
</html>
```

## Relevant Links

Possibly related #879 

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, webpack, and html-webpack-plugin. Run the following to get it quickly:

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v9.4.0
darwin 17.4.0

$ npm --version
5.7.1

$ npm ls webpack
webpack@4.1.0

$ npm ls html-webpack-plugin
html-webpack-plugin@3.0.5
```

**Comment by kagawagao** [comment]
this is caused by [`WebpackCdnPlugin`](https://github.com/van-nguyen/webpack-cdn-plugin/blob/master/module.js#L37)

**Comment by Gisleburt** [comment]
The error comes from there but it's a problem with the [html-webpack-plugin event](https://github.com/jantimon/html-webpack-plugin#events) surely?

**Comment by kagawagao** [comment]
No, it should call the `html-webpack-plugin-before-html-generation` event in `webpack v4` way, like this:
```javascript
compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('WebpackCdnPlugin', (data, callback) => {
  // do something
  callback(null, data)
})
```

- `tapAsync` for `callback` way
- `tap` for sync
- `tapPromise` for `Promise`

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by Gisleburt** [comment]
OK. I'll pop an issue over to them. Thanks for clarifying. 😄

**Comment by mastilver** [comment]
Just FYI, `webpack-cdn-plugin` is a fork of https://github.com/mastilver/dynamic-cdn-webpack-plugin

I just released `dynamic-cdn-webpack-plugin@4.0.0-rc.1` with webpack@4 support, let me know if you have any issues with it
